apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: orders-runner
  namespace: test
spec:
  serviceAccountName: rawan-docker
  taskRef:
    name: orders
  params:
  - name: IMAGE
    value: "rawan005/orders"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: orders-src
