apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: payment-runner
  namespace: test
spec:
  serviceAccountName: rawan-docker
  taskRef:
    name: payment
  params:
  - name: IMAGE
    value: "rawan005/payment"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: payment-re
