apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: queue-runner
  namespace: test
spec:
  serviceAccountName: rawan-docker
  taskRef:
    name: queue-master
  params:
  - name: IMAGE
    value: "rawan005/queuemaster"
  resources:
    inputs:
    - name: queue-m
      resourceRef:
        name: queue-m
