apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: shipment-runner
  namespace: test
spec:
  serviceAccountName: rawan-docker
  taskRef:
    name: shipment
  params:
  - name: IMAGE
    value: "rawan005/ship"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: ship-re
