apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: front-end-runner
  namespace: test
spec:
  serviceAccountName: rawan-docker
  taskRef:
    name: front-end
  params:
  - name: IMAGE
    value: "rawan005/front-end"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: front-end-re
