apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: edge-runner
  namespace: test
spec:
  serviceAccountName: rawan-docker
  taskRef:
    name: edge
  params:
  - name: IMAGE
    value: "rawan005/edge"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: project-level3
