apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: user-db-runner
  namespace: test
spec:
  serviceAccountName: rawan-docker
  taskRef:
    name: user-db
  params:
  - name: IMAGE
    value: "rawan005/user-db"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: user-db-src


