apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: catalogue-runner
  namespace: test
spec:
  serviceAccountName: rawan-docker
  taskRef:
    name: catalogue
  params:
  - name: IMAGE
    value: "rawan005/catalogue"
  resources:
    inputs:
    - name: project-level3
      resourceRef:
        name: catalogue
